# Generated by Django 5.1.1 on 2024-10-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_list',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
